//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertPlaylist
    {
        public int ID { get; set; }
        public int AlertPlaylistID { get; set; }
        public byte ClientID { get; set; }
        public bool Enabled { get; set; }
        public bool PlayIntroAnimation { get; set; }
        public int Repeat { get; set; }
        public byte NumberOfGraphicsBetween { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public Nullable<byte> ExpiresIn { get; set; }
        public int ExpirationMode { get; set; }
        public bool Paused { get; set; }
        public int SortOrder { get; set; }
    }
}
