//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public int ID { get; set; }
        public int GameID { get; set; }
        public int AlertID { get; set; }
        public System.DateTime AlertTimeStamp { get; set; }
        public string Alert1 { get; set; }
    }
}
