//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLog
    {
        public long ID { get; set; }
        public int ClientID { get; set; }
        public string Client { get; set; }
        public string EntryType { get; set; }
        public string Entry { get; set; }
        public string Temperature { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
