//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditorialStatsListDetail
    {
        public Nullable<int> StatsListID { get; set; }
        public int StatsListDetailsID { get; set; }
        public Nullable<int> SDMSportID { get; set; }
        public Nullable<int> SDMLeagueID { get; set; }
        public Nullable<int> SDMTeamID { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string StatsType { get; set; }
        public Nullable<int> StatsTypeID { get; set; }
        public string SDMTeamCode { get; set; }
        public string SDMTeamName { get; set; }
        public string SDMSportsName { get; set; }
        public string SDMLeagueName { get; set; }
        public string TeamType { get; set; }
        public string LeagueCode { get; set; }
        public string PlayerFirstName { get; set; }
        public string PlayerLastName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string SourceType { get; set; }
    }
}
