//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditorialStatsList
    {
        public int StatsListID { get; set; }
        public string StatsListName { get; set; }
        public Nullable<System.DateTime> GameDate { get; set; }
        public Nullable<int> GameID { get; set; }
        public string HiveID { get; set; }
        public string HomeTeamHeader { get; set; }
        public string VisitorTeamHeader { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> ClientID { get; set; }
    }
}
