//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episode
    {
        public int Id { get; set; }
        public Nullable<int> ShowId { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProductionNumber { get; set; }
        public string Year { get; set; }
        public Nullable<int> Season { get; set; }
        public string FoxEpisodeNumber { get; set; }
        public Nullable<System.DateTime> FirstAirDate { get; set; }
        public string BroadcastRating { get; set; }
        public string EpisodeAKATitle { get; set; }
        public string RepeatAirDates { get; set; }
        public string Directors { get; set; }
        public string Actors { get; set; }
        public string Writers { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string Language { get; set; }
        public string VersionDescription { get; set; }
        public string Synopsys { get; set; }
        public string EpisodeNotes { get; set; }
        public int DurationMinutes { get; set; }
        public int DurationSeconds { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
