//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GroupGames = new HashSet<GroupGame>();
        }
    
        public int ID { get; set; }
        public int SportID { get; set; }
        public long StatsIncID { get; set; }
        public int VisitorsID { get; set; }
        public int HomeID { get; set; }
        public int VisitorsScore { get; set; }
        public int HomeScore { get; set; }
        public byte GameStatusID { get; set; }
        public int StatusID { get; set; }
        public string Clock { get; set; }
        public Nullable<System.DateTime> GameDateTime { get; set; }
        public bool BoxScore { get; set; }
        public string Details { get; set; }
        public Nullable<byte> ScoreAlertID { get; set; }
        public Nullable<int> LastVisitorsScore { get; set; }
        public Nullable<int> LastHomeScore { get; set; }
        public string DetailsPreScore { get; set; }
        public string DetailsPostScore { get; set; }
        public Nullable<int> StatusIDPreScore { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string Header { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string ScoreDescription { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool BlockData { get; set; }
        public Nullable<System.DateTime> ScoreLastUpdated { get; set; }
        public string ScoreDescriptionAlt { get; set; }
        public Nullable<int> CSSID { get; set; }
        public string HiveID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupGame> GroupGames { get; set; }
    }
}
