//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameOverride
    {
        public int ID { get; set; }
        public string League { get; set; }
        public string CorrelationID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string NetworkType { get; set; }
        public Nullable<System.DateTime> DateTimeUtc { get; set; }
        public string GameDetails { get; set; }
    }
}
