//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string RunDay { get; set; }
        public int RunHour { get; set; }
        public int RunMinute { get; set; }
        public bool Force { get; set; }
        public System.DateTime LastRun { get; set; }
        public string LastFileDate { get; set; }
        public bool LastSuccess { get; set; }
        public string LastMessage { get; set; }
    }
}
