//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaguesStanding
    {
        public int Id { get; set; }
        public string LeagueCode { get; set; }
        public string Conference { get; set; }
        public string Division { get; set; }
        public string Label { get; set; }
        public string Group { get; set; }
        public int DisplayOrder { get; set; }
    }
}
