//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAlert
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public string OnAirName { get; set; }
        public string Header { get; set; }
        public string Alert { get; set; }
        public Nullable<System.DateTime> AlertDate { get; set; }
        public Nullable<int> PlayCount { get; set; }
        public bool Active { get; set; }
        public string CreatedIP { get; set; }
    }
}
