//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int ID { get; set; }
        public int StatsIncID { get; set; }
        public int TeamID { get; set; }
        public int StatsIncTeamID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Birthday { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string Jersey { get; set; }
        public string Country { get; set; }
    }
}
