//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppressedGame
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string LeagueCode { get; set; }
        public string CorrelationId { get; set; }
        public string GameDate { get; set; }
        public int PlaylistID { get; set; }
    }
}
