//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxSportsDataWrapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDProductionReport
    {
        public int ID { get; set; }
        public Nullable<int> PCR { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TD { get; set; }
        public string Show { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Break1Called { get; set; }
        public Nullable<System.DateTime> Break1Time { get; set; }
        public Nullable<short> Break1Duration { get; set; }
        public Nullable<bool> Break2Called { get; set; }
        public Nullable<System.DateTime> Break2Time { get; set; }
        public Nullable<short> Break2Duration { get; set; }
        public Nullable<bool> Break3Called { get; set; }
        public Nullable<System.DateTime> Break3Time { get; set; }
        public Nullable<short> Break3Duration { get; set; }
        public Nullable<bool> Break4Called { get; set; }
        public Nullable<System.DateTime> Break4Time { get; set; }
        public Nullable<short> Break4Duration { get; set; }
        public Nullable<bool> Meal1Called { get; set; }
        public Nullable<System.DateTime> Meal1Time { get; set; }
        public Nullable<System.TimeSpan> Meal1Duration { get; set; }
        public Nullable<bool> Meal2Called { get; set; }
        public Nullable<System.DateTime> Meal2Time { get; set; }
        public Nullable<System.TimeSpan> Meal2Duration { get; set; }
        public string Jib4Operator { get; set; }
        public string Cam1Operator { get; set; }
        public string Cam2Operator { get; set; }
        public string Cam3Operator { get; set; }
        public string StcOperator { get; set; }
        public string Cam6Operator { get; set; }
        public Nullable<System.DateTime> ShowWrapTime { get; set; }
        public Nullable<bool> BlackOutRouters { get; set; }
        public Nullable<bool> EndOfDayTurnOffMonitorWallProjector { get; set; }
    }
}
